# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_make_inital_stories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reloads', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'reload',
            },
        ),
    ]
